spring:
  datasource:
    url: jdbc:mysql://192.168.85.34:3306/zs_ci?characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;
    username: buynow
    password: buynow
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
#MyBatis配置文件
mybatis:
  typeAliasesPackage: com.harmonycloud.bbs.entity
  mapperLocations: classpath:/sqlmap/mapper/*.xml
  configLocation: classpath:/sqlmap/mybatis-config.xml
cors:
  allowed-origins: '*'
  allowed-headers: Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,\
    Access-Control-Request-Headers,X-AIYANGNIU-SIGNATURE

  allowed-methods: GET,POST,PUT,DELETE,HEAD,OPTIONS
  max-age: 3600
server:
  port: 8081
jenkins:
  host: http://10.10.101.49
  port: 8080
  username: admin
  password: admin
